-- Add your sql here
WITH
T1 AS (SELECT * FROM CUSTOMERS),
T2 AS (SELECT * FROM ORDERS),
T3 AS (SELECT *, (PRICE_PER_MONTH*SUBSCRIPTION_LENGTH) AS Amt_Due FROM SUBSCRIPTIONS)
SELECT
--*,
T1.CUSTOMER_NAME,
--T1.CUSTOMER_ID,
--T2.PURCHASE_DATE,
--T2.SUBSCRIPTION_ID,
--T2.ORDER_STATUS,
--T3.DESCRIPTION,
--T3.PRICE_PER_MONTH,
--T3.SUBSCRIPTION_LENGTH,
SUM(T3.Amt_due) AS Amount_Due
FROM T1
JOIN T2 ON T1.CUSTOMER_ID = T2.CUSTOMER_ID
JOIN T3 ON T2.SUBSCRIPTION_ID = T3.SUBSCRIPTION_ID
WHERE T2.ORDER_STATUS='unpaid'
GROUP BY 
T1.CUSTOMER_NAME;
